CREATE TABLE dbo.BANK_MOVEMENTS
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ISLEM_NO NVARCHAR(100) NOT NULL,
    ISLEM_TARIH_ZAMANI DATETIME2 NOT NULL,
    TUTAR DECIMAL(18,2) NOT NULL,
    BORC_ALACAK CHAR(1) NOT NULL,
    ACIKLAMA NVARCHAR(1000) NULL,
    GONDEREN_IBAN NVARCHAR(34) NULL,
    HESAP_NO NVARCHAR(50) NOT NULL,
    CLIENT_NO NVARCHAR(50) NULL,
    NETWORK_ID NVARCHAR(50) NOT NULL,
    BANK_NAME NVARCHAR(50) NOT NULL,
    PROCESSED_AT DATETIME2 NOT NULL,
    CREATED_AT DATETIME2 NOT NULL
        CONSTRAINT DF_BANK_MOVEMENTS_CREATED_AT DEFAULT SYSUTCDATETIME(),

    CONSTRAINT UQ_BANK_MOVEMENTS_TRANSACTION
        UNIQUE (ISLEM_NO, BANK_NAME, NETWORK_ID),

    CONSTRAINT CK_BANK_MOVEMENTS_BORC_ALACAK
        CHECK (BORC_ALACAK IN ('A', 'B'))
);

CREATE INDEX IX_BANK_MOVEMENTS_ISLEM_TARIH ON dbo.BANK_MOVEMENTS (ISLEM_TARIH_ZAMANI DESC);
CREATE INDEX IX_BANK_MOVEMENTS_BANK_NETWORK ON dbo.BANK_MOVEMENTS (BANK_NAME, NETWORK_ID);
CREATE INDEX IX_BANK_MOVEMENTS_CREATED_AT ON dbo.BANK_MOVEMENTS (CREATED_AT DESC);
